# This is a basic workflow to help you get started with Actions

name: Send Email

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule event but only for the main branch
  schedule:
    - cron: '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install java
        run: |
          sudo apt update
          sudo apt install default-jre
          
      - name: Install jar from github release
        run: curl https://github.com/mvvrachev/ParkingSystemEmailSender/releases/download/email-sender-0.4/EmailSender.jar -L --output EmailSender.jar
        
      - name: Echo file
        run: |
          echo "${{ secrets.FIREBASEADMIN_JSON }}" > credentials.json
          cat credentials.json
        
      - name: Run jar
        run: java -jar EmailSender.jar
